#!/bin/bash

set -ex

#function datacontract() {
#    docker run --rm -v "${PWD}:/home/datacontract" --platform linux/amd64 datacontract/cli:latest "$@"
#}

datacontract --version

SCHEMA=datacontract.schema.json

awk '/^```yaml$/{flag=1; next} /^```$/{print ""; flag=0; exit} flag' README.md > datacontract-from-readme.yaml
datacontract lint datacontract-from-readme.yaml --schema $SCHEMA
datacontract test --examples datacontract-from-readme.yaml --schema $SCHEMA
# Compare with example?

datacontract lint examples/orders-latest/datacontract.yaml --schema $SCHEMA
datacontract test --examples examples/orders-latest/datacontract.yaml --schema $SCHEMA

datacontract lint examples/orders-latest-nested/datacontract.yaml --schema $SCHEMA
datacontract test --examples examples/orders-latest-nested/datacontract.yaml --schema $SCHEMA || true # examples are not nested

datacontract lint examples/covid-cases/datacontract.yaml --schema $SCHEMA
datacontract test --examples examples/covid-cases/datacontract.yaml --schema $SCHEMA || true

